# Setup
title:               Yoon's Blog
tagline:             '상암동 개발자 윤상혁의 블로그'
description:         ''
url:                 https://sanghyukyoon.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              SanghyukYoon
  url:               https://www.instagram.com/y_sanghyuk/
  email:             xxy00@mocomsys.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-SXB9LB6D2P
